---
title: "`r paste0('Liz Roten ', ifelse(params$resume_mode == TRUE, 'Resumé', 'CV'))`"
author: Liz Roten
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
  resume_mode:
    value: false
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

# remotes::install_github("nstrayer/datadrivencv#86")
# remotes::install_github("mitchelloharawild/icons")

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "data/",  
  pdf_mode = params$pdf_mode,
  resume = params$resume_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
cat("<br>")
CV %>% print_contact_info(contact_option = "icons")
```

```{r}
if(params$pdf_mode){
  if(params$resume_mode){
    cat("View this resumé online with links at [_lizroten.com_](https://lizroten.com)")
  } else {
    cat("View this CV online with links at [_lizroten.com_](https://lizroten.com)")
  }
} else {
  if(params$resume_mode){
    cat("[<i class='fas fa-download'></i> Download a PDF of this resumé](https://github.com/eroten/cv/raw/main/resume.pdf)")
  } else {
    cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/eroten/cv/raw/main/cv.pdf)")
  }
}
```

Key Skills {#skills}
--------------------------------------------------------------------------------
- R  
- R Shiny
- R package development
- Quarto
- HTML/CSS, JavaScript  
- Tableau  
- Adobe Illustrator  
- VS Code  
- JavaScript  
- Git/GitHub  
- ESRI Products  
- Project management  



Open Source Contributions {#open-source}
--------------------------------------------------------------------------------

- [`councilR`](https://github.com/Metropolitan-Council/councilR) Organization specific package for consistent style and data practices.  
- [`streetlightR`](https://github.com/Metropolitan-Council/streetlightR) R wrapper for  StreetLight InSight® API.
- [`covid-poops`](https://github.com/Metropolitan-Council/covid-poops) Shiny app for monitoring COVID-19 viral presence in metro wastewater.


Main
================================================================================

Liz Roten {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
# CV %<>% print_text_block('industy_experience_aside')
```
:::

```{r}
CV %<>% print_section('industry_positions')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Select projects and talks{data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('projects_talks')
```

\newpage
Select Data Science Writing {data-icon=chart-line}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('data_science_writing_aside')
```
:::

```{r}
CV %<>% print_section('data_science_writings')
```

\newpage
Awards {data-icon=trophy}
--------------------------------------------------------------------------------
```{r}
CV %<>% print_section('awards')
```

<!-- print links -->
::: aside
```{r}
CV %<>% print_links()
```
:::
